/**
 * worker.mjs — ApexLogics MCP Server (Cloudflare Worker)
 * Endpoint: https://mcp.apexlogics.org/mcp
 *
 * Uses McpServer (SDK 1.29.0) for tool registration + protocol compliance.
 * Uses a custom StatelessFetchTransport that bridges the CF Workers Fetch API
 * to the SDK's Transport interface without requiring fetch-to-node or Node.js
 * ServerResponse. Each request gets a fresh server instance (stateless).
 *
 * Data fixtures are pre-generated by generate.mjs and bundled at deploy time.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { TOOL_SCHEMAS } from "./pilot.mjs";
import { executionHash } from "./_hash.mjs";
import { runChain } from "./run_chain.mjs";
import toolsData from "./data/tools.json" with { type: "json" };
import workflowsData from "./data/workflows.json" with { type: "json" };
import chaingraphData from "./data/chaingraph/chaingraph.json" with { type: "json" };
import pkg from "./package.json" with { type: "json" };

// toolsData mixes two distinct catalogs (per suite-registry.json's own "showcase"
// category): calculator tools and OCG-Industries showcase exemplars. Suite-wide
// convention (apexlogics.org) reports these as two separate counts, never one
// combined figure -- so anywhere this file describes "the suite" in prose, use
// CALC_TOOL_COUNT, not the raw array length.
const CALC_TOOL_COUNT = toolsData.filter((t) => t.category !== "showcase").length;
const SHOWCASE_COUNT = toolsData.length - CALC_TOOL_COUNT;

// package.json is the SSOT for version — server.json is kept in sync by hand
// (checked at deploy time) since it's registry-facing static metadata, not
// worker-bundled code.
const SERVER_META = { name: "apexlogics-tools", version: pkg.version };

// ── MCP 2026-07-28 protocol layer (AL-MCP-728-A) ─────────────────────────────
// The SDK (1.29) speaks the 2025-x eras only, so version negotiation, the
// server/discover MUST, the unknown-tool error SHAPE, and the resultType stamp
// are all handled AHEAD of the transport. Dual-era: modern clients carry
// version/capabilities in params._meta (SEP-2575 removed the handshake), while
// legacy `initialize` clients keep working through the SDK path for the full
// twelve-month window.

const PROTOCOL_VERSION = "2026-07-28";
const LEGACY_PROTOCOL_VERSION = "2025-06-18";
const SUPPORTED_PROTOCOL_VERSIONS = [PROTOCOL_VERSION, LEGACY_PROTOCOL_VERSION];
const PROTOCOL_SUNSET = "2027-07-28"; // twelve months from the 2026-07-28 release

const META_PROTOCOL_VERSION = "io.modelcontextprotocol/protocolVersion";
const META_SERVER_INFO = "io.modelcontextprotocol/serverInfo";
const META_DEPRECATION = "org.apexlogics/protocolDeprecation";

const SERVER_CAPABILITIES = { tools: { listChanged: true } };

const SERVER_INFO_META = {
  name: SERVER_META.name,
  version: SERVER_META.version,
  title: "ApexLogics MCP",
  websiteUrl: "https://apexlogics.org",
};

// Machine-readable notice handed to every old-protocol client. Dated, not a
// cron: the sunset is a record, and removal is a future WU, never automatic.
const LEGACY_DEPRECATION_NOTICE = {
  status: "deprecated",
  deprecatedVersion: LEGACY_PROTOCOL_VERSION,
  supersededBy: PROTOCOL_VERSION,
  sunsetDate: PROTOCOL_SUNSET,
  supportedVersions: SUPPORTED_PROTOCOL_VERSIONS,
  message:
    "This client opened the connection with the pre-2026-07-28 initialize handshake. That era stays supported until 2027-07-28. Move to 2026-07-28 by sending params._meta['io.modelcontextprotocol/protocolVersion'] on each request instead of initialize.",
};

// Every method this server actually implements. Anything else over HTTP is a
// 404 plus -32601 (a status change under the final text, not just a body one).
// Notifications are id-less and never reach this gate -- they still 204.
const KNOWN_METHODS = new Set([
  "initialize",
  "ping",
  "tools/list",
  "tools/call",
  "server/discover",
]);

const SERVER_INSTRUCTIONS =
  `ApexLogics is a ${CALC_TOOL_COUNT}-tool edtech and careertech suite, plus ${SHOWCASE_COUNT} OCG-Industries showcase exemplars. Use find_tool for a ranked search when you need one specific calculator, find_chain for a ranked search when the goal spans several tools, and run_chain to execute a chain server-side. list_apexlogics_tools returns the full unranked catalog (tools + showcase); build_workflow_links returns deep-link workflow pages.`;

// ── OCG Standard §4 — execution-hash verification ────────────────────────────
// Preimage canonicalization is the vendored SSOT _hash.mjs (RFC 8785 JCS +
// SHA-256 over {policy_parameters, output_payload}). executionHash() returns
// BARE lowercase hex — byte-identical to AINumbers/OCS so any artifact verifies
// anywhere. CUTOVER 2026-07-04: pre-cutover ApexLogics artifacts carried a
// "sha256:" prefix on the SAME hex payload; normHash() strips the optional
// prefix on BOTH sides so OLD (prefixed) and NEW (bare) artifacts both verify
// through one code path. See CHAINGRAPH-ADOPTION.md hash-cutover note.
const normHash = (h) => (typeof h === "string" ? h.replace(/^sha256:/, "") : h);

// ── Discovery layer — BM25 over the catalog (find_tool) and chains (find_chain) ─
// Index built once at module load (123 tools + 38 chains — cheap; no precomputed
// data file, so nothing to keep fresh). Workers-runtime safe: plain arithmetic only.
// Ported from the AINumbers mcp-apps-poc discovery region (SSOT reference; not forked).
function tokenizeForIndex(text) {
  return (text ?? "").toLowerCase()
    .replace(/[^a-z0-9_-]/g, " ")
    .split(/\s+/)
    .filter((t) => t.length > 1);
}

function buildIndex(docs, getText) {
  const N = docs.length;
  const tfs = docs.map((doc) => {
    const counts = {};
    for (const t of tokenizeForIndex(getText(doc))) counts[t] = (counts[t] || 0) + 1;
    return counts;
  });
  const docLengths = tfs.map((tf) => Object.values(tf).reduce((s, c) => s + c, 0));
  const avgDocLength = docLengths.reduce((s, c) => s + c, 0) / N || 1;
  const df = {};
  for (const tf of tfs) for (const t of Object.keys(tf)) df[t] = (df[t] || 0) + 1;
  const idf = {};
  for (const [t, f] of Object.entries(df)) idf[t] = Math.log((N - f + 0.5) / (f + 0.5) + 1);
  return { docs, tfs, docLengths, avgDocLength, idf };
}

function bm25Search(query, index, { k1 = 1.2, b = 0.75, topN = 5 } = {}) {
  const terms = tokenizeForIndex(query);
  if (!terms.length) return [];
  const { docs, tfs, docLengths, avgDocLength, idf } = index;
  const scores = new Array(docs.length).fill(0);
  for (const t of terms) {
    const idfScore = idf[t] ?? 0;
    if (!idfScore) continue;
    for (let i = 0; i < docs.length; i++) {
      const tf = tfs[i][t] ?? 0;
      if (!tf) continue;
      scores[i] += idfScore * (tf * (k1 + 1)) / (tf + k1 * (1 - b + b * docLengths[i] / avgDocLength));
    }
  }
  return docs
    .map((doc, i) => ({ doc, score: scores[i] }))
    .filter((r) => r.score > 0)
    .sort((a, c) => c.score - a.score)
    .slice(0, topN);
}

const TOOL_INDEX = buildIndex(toolsData, (t) =>
  [t.title, t.description, t.category, t.al_id, t.slug].filter(Boolean).join(" ")
);
const CHAIN_INDEX = buildIndex(chaingraphData.chains ?? [], (c) =>
  [c.name, c.title, c.persona, ...(c.steps ?? []).map((s) => s.tool_id)].filter(Boolean).join(" ")
);

// ── StatelessFetchTransport ───────────────────────────────────────────────────
// Bridges the CF Workers Fetch API to the MCP SDK Transport interface.
// Each instance handles exactly one request/response cycle.
// The SDK calls send() with the response; handleRequest() waits for it.

class StatelessFetchTransport {
  _pending = new Map();
  onmessage = null;
  onerror = null;
  onclose = null;

  async start() {}
  async close() {}

  // Called by McpServer to deliver a response or notification
  async send(message) {
    const id = message?.id;
    if (id !== undefined && id !== null) {
      const resolve = this._pending.get(String(id));
      if (resolve) {
        resolve(message);
        this._pending.delete(String(id));
      }
    }
  }

  // Entry point from the fetch handler
  async handleRequest(req) {
    let body;
    try {
      body = await req.json();
    } catch {
      return Response.json(
        { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } },
        { status: 400, headers: CORS_HEADERS }
      );
    }

    // Notifications have no id — deliver and return 204
    if (body.id === undefined || body.id === null) {
      this.onmessage?.(body);
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    // Requests — register response promise BEFORE delivering message
    const responsePromise = new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`MCP timeout: no response for id=${body.id} method=${body.method}`)),
        10000
      );
      this._pending.set(String(body.id), (msg) => {
        clearTimeout(timer);
        resolve(msg);
      });
    });

    try {
      this.onmessage?.(body);
    } catch (e) {
      this._pending.delete(String(body.id));
      return Response.json(
        { jsonrpc: "2.0", id: body.id, error: { code: -32603, message: e.message } },
        { status: 500, headers: CORS_HEADERS }
      );
    }

    const response = await responsePromise;
    return Response.json(stampResult(response, body), { headers: CORS_HEADERS });
  }
}

// ── CORS ─────────────────────────────────────────────────────────────────────

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Accept, MCP-Protocol-Version",
};

// ── Protocol interception (runs BEFORE the SDK transport) ────────────────────

function jsonRpcError(id, code, message, status, data) {
  const error = { code, message };
  if (data !== undefined) error.data = data;
  return Response.json(
    { jsonrpc: "2.0", id: id ?? null, error },
    { status, headers: CORS_HEADERS }
  );
}

function jsonRpcResult(id, result) {
  return Response.json(
    { jsonrpc: "2.0", id: id ?? null, result },
    { headers: CORS_HEADERS }
  );
}

// The version the client is asking for: modern clients put it in params._meta,
// legacy clients in initialize's params.protocolVersion. null = unstated.
function requestedProtocolVersion(body) {
  const fromMeta = body?.params?._meta?.[META_PROTOCOL_VERSION];
  if (typeof fromMeta === "string") return fromMeta;
  if (body?.method === "initialize") {
    const fromInit = body?.params?.protocolVersion;
    if (typeof fromInit === "string") return fromInit;
  }
  return null;
}

function discoverResult() {
  return {
    supportedVersions: SUPPORTED_PROTOCOL_VERSIONS,
    capabilities: SERVER_CAPABILITIES,
    instructions: SERVER_INSTRUCTIONS,
    ttlMs: 3_600_000,
    cacheScope: "global",
    resultType: "complete",
    _meta: {
      [META_SERVER_INFO]: SERVER_INFO_META,
      [META_DEPRECATION]: LEGACY_DEPRECATION_NOTICE,
    },
  };
}

// A 2026-07-28 client that still opens with `initialize` must be answered with
// 2026-07-28. Left to the SDK it would negotiate DOWN to its own latest era and
// echo a version this server does not implement -- the exact defect class the
// final text forbids.
function modernInitializeResult() {
  return {
    protocolVersion: PROTOCOL_VERSION,
    capabilities: SERVER_CAPABILITIES,
    serverInfo: { ...SERVER_META },
    instructions: SERVER_INSTRUCTIONS,
    resultType: "complete",
    _meta: { [META_SERVER_INFO]: SERVER_INFO_META },
  };
}

// Returns a Response to send instead of running the SDK, or null to continue.
function interceptProtocol(body) {
  if (!body || typeof body !== "object") return null;
  const id = body.id;
  const isRequest = id !== undefined && id !== null;
  const method = body.method;

  // Version negotiation ahead of the SDK's negotiate-down. Never echo a version
  // we do not implement.
  const asked = requestedProtocolVersion(body);
  if (asked !== null && !SUPPORTED_PROTOCOL_VERSIONS.includes(asked)) {
    return jsonRpcError(
      id,
      -32022,
      `Unsupported protocol version: ${asked}`,
      400,
      { supported: SUPPORTED_PROTOCOL_VERSIONS, requested: asked }
    );
  }

  if (!isRequest) return null; // notifications keep their 204 path

  if (method === "server/discover") {
    return jsonRpcResult(id, discoverResult());
  }

  if (method === "initialize" && asked === PROTOCOL_VERSION) {
    return jsonRpcResult(id, modernInitializeResult());
  }

  // Unknown tool is a PROTOCOL error -- a JSON-RPC error object with -32602,
  // not an isError tool result. SDK 1.29 wraps its own -32602 into a tool
  // result (server/mcp.js createToolError), so the check has to happen here.
  if (method === "tools/call") {
    const name = body?.params?.name;
    if (typeof name !== "string" || !Object.hasOwn(TOOL_SCHEMAS, name)) {
      return jsonRpcError(id, -32602, `Unknown tool: ${name ?? "(missing)"}`, 200);
    }
  }

  if (!KNOWN_METHODS.has(method)) {
    return jsonRpcError(id, -32601, `Method not found: ${method ?? "(missing)"}`, 404);
  }

  return null;
}

// Stamp every SDK success result with resultType + serverInfo, and hand legacy
// initialize clients the machine-readable deprecation notice.
function stampResult(message, requestBody) {
  const result = message?.result;
  if (!result || typeof result !== "object") return message;
  if (result.resultType === undefined) result.resultType = "complete";
  result._meta = { ...(result._meta ?? {}), [META_SERVER_INFO]: SERVER_INFO_META };
  if (requestBody?.method === "initialize") {
    result._meta[META_DEPRECATION] = LEGACY_DEPRECATION_NOTICE;
  }
  return message;
}

// ── Tool handlers ─────────────────────────────────────────────────────────────

function handleListTools({ query, category, limit = 20 }) {
  const q = (query || "").toLowerCase().trim();
  const cat = (category || "").toLowerCase().trim();
  const lim = Math.min(limit, 50);

  let results = toolsData.filter((t) => {
    if (cat && t.category !== cat) return false;
    if (!q) return true;
    const hay = [t.title, t.description, t.al_id, t.slug, t.category]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();
    return q.split(/\s+/).every((term) => hay.includes(term));
  });

  const total = results.length;
  results = results.slice(0, lim);

  return {
    query: q || null,
    category: cat || null,
    total_matches: total,
    returned: results.length,
    tools: results.map((t) => ({
      al_id: t.al_id,
      title: t.title,
      description: t.description,
      category: t.category,
      url: `https://apexlogics.org/tools/${t.slug}/`,
      ap2_type: t.ap2_mandate_type,
      ap2_export: t.ap2_export,
    })),
    _note: total > lim ? `${total - lim} more — refine query or increase limit (max 50)` : null,
  };
}

function handleBuildWorkflow({ workflow }) {
  const name = (workflow || "").toLowerCase().trim();

  if (!name) {
    return {
      available_workflows: Object.entries(workflowsData).map(([id, w]) => ({
        id,
        description: w.description,
        steps: w.steps.length,
      })),
      usage: 'Pass workflow: "<id>" to get ordered deep-links for that chain.',
    };
  }

  const wf = workflowsData[name];
  if (!wf) {
    return { error: `Unknown workflow: "${name}"`, available: Object.keys(workflowsData) };
  }

  return {
    workflow: name,
    description: wf.description,
    workflow_page: `https://apexlogics.org/workflows/${name}.html`,
    steps: wf.steps.map((s, i) => ({
      step: i + 1,
      tool: s.tool,
      note: s.note,
      url: `https://apexlogics.org/tools/${s.tool}/`,
    })),
    _tip: "Run steps in order. Each tool exports an AP2 mandate you can paste into the next tool's import field.",
  };
}

// run_chain — OCG Standard §21. Execute a named chain server-side and return the
// composite artifact + reproducible composite_execution_hash. Omit chain to list
// runnable chains. Non-kernel steps degrade to no_kernel_browser_only (not an error).
async function handleRunChain({ chain, inputs }) {
  const name = (chain || "").trim();
  if (!name) {
    return {
      available_chains: (chaingraphData.chains ?? []).map((c) => ({
        name: c.name,
        title: c.title ?? c.name,
        steps: (c.steps ?? []).length,
      })),
      usage: 'Pass chain: "<name>" to run it server-side. Optionally pass inputs: { "<tool_id>": { ...fields } }.',
    };
  }
  try {
    return await runChain(name, inputs);
  } catch (e) {
    return {
      error: e.message,
      available: (chaingraphData.chains ?? []).map((c) => c.name),
    };
  }
}

// find_tool — ranked BM25 over the tool catalog. For a single calculator; use
// find_chain for multi-step journeys, list_apexlogics_tools for the full list.
function handleFindTool({ query, top_n = 5 }) {
  const q = (query || "").trim();
  const topN = Math.min(Math.max(top_n || 5, 1), 10);
  if (!q) return { error: "Provide a query.", hint: "e.g. 'ISO AMT exposure' or 'teacher pension'." };
  const hits = bm25Search(q, TOOL_INDEX, { topN });
  if (!hits.length) {
    return { query: q, results: [], hint: "No tool matched. Try find_chain for a multi-step goal or list_apexlogics_tools for the full catalog." };
  }
  return {
    query: q,
    returned: hits.length,
    results: hits.map(({ doc: t, score }) => ({
      al_id: t.al_id,
      title: t.title,
      description: t.description,
      category: t.category,
      url: `https://apexlogics.org/tools/${t.slug}/`,
      ap2_type: t.ap2_mandate_type,
      ap2_export: t.ap2_export,
      score: Math.round(score * 1000) / 1000,
    })),
    _tip: "Run a multi-tool journey with find_chain / run_chain.",
  };
}

// find_chain — ranked BM25 over the catalog chains. For multi-step journeys; run a
// match server-side with run_chain, or build_workflow_links for deep-link pages.
function handleFindChain({ query, top_n = 5 }) {
  const q = (query || "").trim();
  const topN = Math.min(Math.max(top_n || 5, 1), 10);
  if (!q) return { error: "Provide a query.", hint: "e.g. 'career pivot' or 'equity exit 83b'." };
  const hits = bm25Search(q, CHAIN_INDEX, { topN });
  if (!hits.length) {
    return { query: q, results: [], hint: "No chain matched. Try find_tool for a single calculator." };
  }
  return {
    query: q,
    returned: hits.length,
    results: hits.map(({ doc: c, score }) => ({
      name: c.name,
      title: c.title ?? c.name,
      persona: c.persona ?? null,
      steps: (c.steps ?? []).map((s) => s.tool_id),
      run: `run_chain(chain: "${c.name}")`,
      score: Math.round(score * 1000) / 1000,
    })),
    _tip: "Execute a match server-side with run_chain, passing its name.",
  };
}

// ── Server factory (new instance per request — stateless) ────────────────────

function buildServer(env) {
  const server = new McpServer({
    ...SERVER_META,
    instructions: SERVER_INSTRUCTIONS,
  });

  server.tool(
    "find_tool",
    TOOL_SCHEMAS.find_tool.description,
    TOOL_SCHEMAS.find_tool.params,
    async (args) => {
      return { content: [{ type: "text", text: JSON.stringify(handleFindTool(args), null, 2) }] };
    }
  );

  server.tool(
    "find_chain",
    TOOL_SCHEMAS.find_chain.description,
    TOOL_SCHEMAS.find_chain.params,
    async (args) => {
      return { content: [{ type: "text", text: JSON.stringify(handleFindChain(args), null, 2) }] };
    }
  );

  server.tool(
    "list_apexlogics_tools",
    TOOL_SCHEMAS.list_apexlogics_tools.description.replace("{COUNT}", String(toolsData.length)),
    TOOL_SCHEMAS.list_apexlogics_tools.params,
    async (args) => {
      return { content: [{ type: "text", text: JSON.stringify(handleListTools(args), null, 2) }] };
    }
  );

  server.tool(
    "build_workflow_links",
    TOOL_SCHEMAS.build_workflow_links.description,
    TOOL_SCHEMAS.build_workflow_links.params,
    async (args) => {
      return { content: [{ type: "text", text: JSON.stringify(handleBuildWorkflow(args), null, 2) }] };
    }
  );

  // verify_execution_hash — OCG Standard §4. Recompute an artifact's execution
  // hash so any agent can independently verify an ApexLogics (or any OCG
  // vendor's) artifact rather than trust it. Vendor-neutral: bare-hex JCS.
  // Normalizes the optional "sha256:" prefix so pre-2026-07-04 (prefixed) and
  // post-cutover (bare) ApexLogics artifacts both verify.
  server.tool(
    "verify_execution_hash",
    TOOL_SCHEMAS.verify_execution_hash.description,
    TOOL_SCHEMAS.verify_execution_hash.params,
    async (args) => {
      const a = args.artifact;
      const pp = args.policy_parameters ?? a?.policy_parameters;
      const op = args.output_payload ?? a?.output_payload;
      const claimed = args.claimed_hash ?? a?.execution_hash ?? null;
      if (pp === undefined || op === undefined) {
        return { content: [{ type: "text", text: "Provide a full artifact, or policy_parameters + output_payload (+ claimed_hash)." }] };
      }
      let computed;
      try {
        computed = await executionHash(pp, op);
      } catch (e) {
        // _hash.mjs assertIJson() rejects non-finite / unsafe-integer values
        // rather than emit an unstable hash — report, do not 500.
        return { content: [{ type: "text", text: JSON.stringify({
          valid: false,
          error: "non-canonical-input",
          detail: e.message,
          note: "policy_parameters/output_payload contain a value outside I-JSON (NaN/Infinity or an integer beyond 2^53). Not hashable under OCG §4; treat as unverified.",
          spec: "OCG Standard §4 (RFC 8785 JCS + SHA-256)",
        }, null, 2) }] };
      }
      const valid = claimed != null && normHash(computed) === normHash(claimed);
      const out = {
        valid,
        computed_hash: computed,
        claimed_hash: claimed,
        tool_id: a?.tool_id ?? null,
        chaingraph_version: a?.chaingraph_version ?? a?.ap2_version ?? null,
        note: claimed == null
          ? "No claimed hash supplied — returning the computed hash only (bare hex, OCG §4)."
          : (valid ? "Verified: recomputed hash matches the artifact (sha256: prefix normalized)." : "MISMATCH: treat the artifact as unverified."),
        spec: "OCG Standard §4 (RFC 8785 JCS + SHA-256)",
      };
      return { content: [{ type: "text", text: JSON.stringify(out, null, 2) }] };
    }
  );

  server.tool(
    "run_chain",
    TOOL_SCHEMAS.run_chain.description,
    TOOL_SCHEMAS.run_chain.params,
    async (args) => {
      return { content: [{ type: "text", text: JSON.stringify(await handleRunChain(args), null, 2) }] };
    }
  );

  return server;
}

// ── Fetch handler ─────────────────────────────────────────────────────────────

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    if (url.pathname === "/healthz" || url.pathname === "/") {
      return Response.json(
        { status: "ok", server: SERVER_META, tools: Object.keys(TOOL_SCHEMAS) },
        { headers: CORS_HEADERS }
      );
    }

    // Agent-directory / MCP-client discovery: served over plain GET before connecting.
    if (url.pathname === "/.well-known/mcp/server-card.json") {
      return Response.json(
        {
          schema_version: "mcp-server-card-v1",
          name: "apexlogics-mcp",
          title: "ApexLogics MCP",
          description:
            `Live MCP endpoint for the ApexLogics edtech and careertech suite: ${CALC_TOOL_COUNT} deterministic, privacy-first calculators plus ${SHOWCASE_COUNT} chainable OpenChainGraph showcase compute nodes with verifiable SHA-256 execution hashes. Ranked catalog search (find_tool / find_chain) and server-side chain execution (run_chain). Zero PII, zero network after page load, zero payload logging.`,
          version: SERVER_META.version,
          publisher: { name: "Post Oak Labs", url: "https://postoaklabs.com" },
          license: "CC-BY-4.0",
          endpoints: [
            {
              url: "https://mcp.apexlogics.org/mcp",
              transport: "streamable-http",
              protocol_version: PROTOCOL_VERSION,
              supported_protocol_versions: SUPPORTED_PROTOCOL_VERSIONS,
              legacy_protocol_sunset: PROTOCOL_SUNSET,
              authentication: "none",
            },
          ],
          capabilities: SERVER_CAPABILITIES,
          registry: "org.apexlogics/tools",
          documentation: "https://apexlogics.org/about.html",
          standard: "https://ainumbers.co/chaingraph/openchain-graph-spec.html",
          llms_txt: "https://apexlogics.org/llms.txt",
        },
        { headers: { ...CORS_HEADERS, "Cache-Control": "public, max-age=3600" } }
      );
    }

    if (url.pathname === "/mcp") {
      if (request.method !== "POST") {
        return Response.json({ error: "POST required" }, { status: 405, headers: CORS_HEADERS });
      }

      // Parse a clone for telemetry — the transport consumes the original request stream.
      // Structural metadata only; never payloads, parameters, or outputs.
      const body = await request.clone().json().catch(() => undefined);
      const isToolCall = body?.method === "tools/call";
      const toolName   = isToolCall ? (body?.params?.name ?? "unknown") : null;
      const chainDepth = isToolCall ? (body?.params?.arguments?.chain_depth ?? 0) : null;
      const t0 = Date.now();

      // 2026-07-28 semantics the SDK cannot serve: version rejection,
      // server/discover, modern initialize, unknown-tool shape, unknown method.
      const intercepted = interceptProtocol(body);
      if (intercepted) return intercepted;

      try {
        const transport = new StatelessFetchTransport();
        const server = buildServer(env);
        await server.connect(transport);
        const response = await transport.handleRequest(request);

        // Fire-and-forget Analytics Engine telemetry — never blocks the response.
        // Salted, non-reversible caller hash (no PII). Mirrors ainumbers-mcp / ocs-mcp.
        if (isToolCall && env.ANALYTICS) {
          const latencyMs = Date.now() - t0;
          const success   = response.status < 500;
          const callerRaw = request.headers.get("CF-Connecting-IP") ?? request.headers.get("X-Forwarded-For") ?? "";
          const callerBuf = await crypto.subtle.digest("SHA-256",
            new TextEncoder().encode("apexlogics-mcp-v1:" + callerRaw));
          const callerHash = "sha256:" + Array.from(new Uint8Array(callerBuf)).map(b => b.toString(16).padStart(2, "0")).join("").slice(0, 16);
          ctx.waitUntil(Promise.resolve().then(() => {
            try {
              env.ANALYTICS.writeDataPoint({
                blobs:   [toolName, callerHash, success ? "ok" : "error"],
                doubles: [latencyMs, chainDepth ?? 0],
                indexes: [toolName],
              });
            } catch (_) { /* telemetry is best-effort; never affect the response */ }
          }));
        }

        return response;
      } catch (e) {
        console.error("mcp transport error", e.stack ?? e.message);
        return Response.json(
          { jsonrpc: "2.0", id: body?.id ?? null, error: { code: -32603, message: "Internal error" } },
          { status: 500, headers: CORS_HEADERS }
        );
      }
    }

    return new Response("Not found", { status: 404, headers: CORS_HEADERS });
  },
};

// Exported for the discovery self-test (scripts) and reuse — no runtime effect on the Worker.
export { handleFindTool, handleFindChain, bm25Search, TOOL_INDEX, CHAIN_INDEX };
