/**
 * worker.mjs — ApexLogics MCP Server (Cloudflare Worker)
 * Endpoint: https://mcp.apexlogics.org/mcp
 *
 * Uses McpServer (SDK 1.29.0) for tool registration + protocol compliance.
 * Uses a custom StatelessFetchTransport that bridges the CF Workers Fetch API
 * to the SDK's Transport interface without requiring fetch-to-node or Node.js
 * ServerResponse. Each request gets a fresh server instance (stateless).
 *
 * Data fixtures are pre-generated by generate.mjs and bundled at deploy time.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { TOOL_SCHEMAS } from "./pilot.mjs";
import toolsData from "./data/tools.json" with { type: "json" };
import workflowsData from "./data/workflows.json" with { type: "json" };

const SERVER_META = { name: "apexlogics-tools", version: "1.0.0" };

// ── StatelessFetchTransport ───────────────────────────────────────────────────
// Bridges the CF Workers Fetch API to the MCP SDK Transport interface.
// Each instance handles exactly one request/response cycle.
// The SDK calls send() with the response; handleRequest() waits for it.

class StatelessFetchTransport {
  _pending = new Map();
  onmessage = null;
  onerror = null;
  onclose = null;

  async start() {}
  async close() {}

  // Called by McpServer to deliver a response or notification
  async send(message) {
    const id = message?.id;
    if (id !== undefined && id !== null) {
      const resolve = this._pending.get(String(id));
      if (resolve) {
        resolve(message);
        this._pending.delete(String(id));
      }
    }
  }

  // Entry point from the fetch handler
  async handleRequest(req) {
    let body;
    try {
      body = await req.json();
    } catch {
      return Response.json(
        { jsonrpc: "2.0", id: null, error: { code: -32700, message: "Parse error" } },
        { status: 400, headers: CORS_HEADERS }
      );
    }

    // Notifications have no id — deliver and return 204
    if (body.id === undefined || body.id === null) {
      this.onmessage?.(body);
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    // Requests — register response promise BEFORE delivering message
    const responsePromise = new Promise((resolve, reject) => {
      const timer = setTimeout(
        () => reject(new Error(`MCP timeout: no response for id=${body.id} method=${body.method}`)),
        10000
      );
      this._pending.set(String(body.id), (msg) => {
        clearTimeout(timer);
        resolve(msg);
      });
    });

    try {
      this.onmessage?.(body);
    } catch (e) {
      this._pending.delete(String(body.id));
      return Response.json(
        { jsonrpc: "2.0", id: body.id, error: { code: -32603, message: e.message } },
        { status: 500, headers: CORS_HEADERS }
      );
    }

    const response = await responsePromise;
    return Response.json(response, { headers: CORS_HEADERS });
  }
}

// ── CORS ─────────────────────────────────────────────────────────────────────

const CORS_HEADERS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, POST, OPTIONS",
  "Access-Control-Allow-Headers": "Content-Type, Accept, MCP-Protocol-Version, Mcp-Session-Id",
  "Access-Control-Expose-Headers": "Mcp-Session-Id",
};

// ── Tool handlers ─────────────────────────────────────────────────────────────

function handleListTools({ query, category, limit = 20 }) {
  const q = (query || "").toLowerCase().trim();
  const cat = (category || "").toLowerCase().trim();
  const lim = Math.min(limit, 50);

  let results = toolsData.filter((t) => {
    if (cat && t.category !== cat) return false;
    if (!q) return true;
    const hay = [t.title, t.description, t.al_id, t.slug, t.category]
      .filter(Boolean)
      .join(" ")
      .toLowerCase();
    return q.split(/\s+/).every((term) => hay.includes(term));
  });

  const total = results.length;
  results = results.slice(0, lim);

  return {
    query: q || null,
    category: cat || null,
    total_matches: total,
    returned: results.length,
    tools: results.map((t) => ({
      al_id: t.al_id,
      title: t.title,
      description: t.description,
      category: t.category,
      url: `https://apexlogics.org/tools/${t.slug}/`,
      ap2_type: t.ap2_mandate_type,
      ap2_export: t.ap2_export,
    })),
    _note: total > lim ? `${total - lim} more — refine query or increase limit (max 50)` : null,
  };
}

function handleBuildWorkflow({ workflow }) {
  const name = (workflow || "").toLowerCase().trim();

  if (!name) {
    return {
      available_workflows: Object.entries(workflowsData).map(([id, w]) => ({
        id,
        description: w.description,
        steps: w.steps.length,
      })),
      usage: 'Pass workflow: "<id>" to get ordered deep-links for that chain.',
    };
  }

  const wf = workflowsData[name];
  if (!wf) {
    return { error: `Unknown workflow: "${name}"`, available: Object.keys(workflowsData) };
  }

  return {
    workflow: name,
    description: wf.description,
    workflow_page: `https://apexlogics.org/workflows/${name}.html`,
    steps: wf.steps.map((s, i) => ({
      step: i + 1,
      tool: s.tool,
      note: s.note,
      url: `https://apexlogics.org/tools/${s.tool}/`,
    })),
    _tip: "Run steps in order. Each tool exports an AP2 mandate you can paste into the next tool's import field.",
  };
}

// ── Telemetry helper ──────────────────────────────────────────────────────────
// CF Analytics Engine writeDataPoint is synchronous + fire-and-forget.
// Schema: blobs[0]=tool, blobs[1]=param1, blobs[2]=param2, doubles[0]=1.
// indexes[0] enables fast GROUP BY tool_name in Workers Analytics Engine SQL.
// Optional-chained so local dev (no AE binding) silently no-ops.

function track(env, tool, param1 = "", param2 = "") {
  try {
    env.AE?.writeDataPoint({
      blobs: [tool, param1, param2],
      doubles: [1],
      indexes: [tool],
    });
  } catch (_) {
    // never let telemetry errors surface to callers
  }
}

// ── Server factory (new instance per request — stateless) ────────────────────

function buildServer(env) {
  const server = new McpServer({
    ...SERVER_META,
    instructions:
      `ApexLogics is a ${toolsData.length}-tool edtech and careertech suite. Use list_apexlogics_tools to find the right calculator for any career, education, compensation, licensing, or immigration question. Use build_workflow_links to chain tools together for multi-step analyses.`,
  });

  server.tool(
    "list_apexlogics_tools",
    TOOL_SCHEMAS.list_apexlogics_tools.description.replace("{COUNT}", String(toolsData.length)),
    TOOL_SCHEMAS.list_apexlogics_tools.params,
    async (args) => {
      track(env, "list_apexlogics_tools", args.query || "", args.category || "");
      return { content: [{ type: "text", text: JSON.stringify(handleListTools(args), null, 2) }] };
    }
  );

  server.tool(
    "build_workflow_links",
    TOOL_SCHEMAS.build_workflow_links.description,
    TOOL_SCHEMAS.build_workflow_links.params,
    async (args) => {
      track(env, "build_workflow_links", args.workflow || "_index");
      return { content: [{ type: "text", text: JSON.stringify(handleBuildWorkflow(args), null, 2) }] };
    }
  );

  return server;
}

// ── Fetch handler ─────────────────────────────────────────────────────────────

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    if (request.method === "OPTIONS") {
      return new Response(null, { status: 204, headers: CORS_HEADERS });
    }

    if (url.pathname === "/healthz" || url.pathname === "/") {
      return Response.json(
        { status: "ok", server: SERVER_META, tools: Object.keys(TOOL_SCHEMAS) },
        { headers: CORS_HEADERS }
      );
    }

    if (url.pathname === "/mcp") {
      if (request.method !== "POST") {
        return Response.json({ error: "POST required" }, { status: 405, headers: CORS_HEADERS });
      }

      try {
        const transport = new StatelessFetchTransport();
        const server = buildServer(env);
        await server.connect(transport);
        return await transport.handleRequest(request);
      } catch (e) {
        return Response.json(
          { error: e.message, stack: e.stack },
          { status: 500, headers: CORS_HEADERS }
        );
      }
    }

    return new Response("Not found", { status: 404, headers: CORS_HEADERS });
  },
};
